//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AES
    {
        public int idAes { get; set; }
        public int idUsuario { get; set; }
        public string token { get; set; }
        public string iv { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
