//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolOpcion
    {
        public int idRolOpcion { get; set; }
        public int idOpcion { get; set; }
        public int idRol { get; set; }
    
        public virtual Opcion Opcion { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
