//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rol_user
    {
        public int idUserRol { get; set; }
        public int idUser { get; set; }
        public string userName { get; set; }
        public int idRol { get; set; }
        public string rolName { get; set; }
    }
}
